language: node_js
node_js:
  - node
sudo: false
cache: yarn
git:
  submodules: false

env:
  global:
    - DEPLOY=true
    - DEPLOY_FILE="$TRAVIS_BUILD_DIR/../release-front-$TRAVIS_TAG.tbz2"

before_install:
  - if [ "$TRAVIS_SECURE_ENV_VARS" == "true" ]; then
      openssl aes-256-cbc -K $encrypted_0e7677705f90_key -iv $encrypted_0e7677705f90_iv -in gh_rsa.enc -out gh_rsa -d;
    fi

install:
  - yarn add minifyjs babel-cli babel-preset-env
  - git submodule update --init --recursive

script:
  - make

after_success:
  - if [ "$TRAVIS_SECURE_ENV_VARS" == "true" ]; then
      (
        echo "Update release for commits $TRAVIS_COMMIT_RANGE";
        echo;
        git log $TRAVIS_COMMIT_RANGE --pretty=oneline;
      ) >> $TRAVIS_BUILD_DIR/../RELEASE_UPDATE_MSG;
      mkdir -p ~/.ssh && cp gh_rsa ~/.ssh/id_rsa && chmod 700 ~/.ssh && chmod 600 ~/.ssh/id_rsa;
      git clone -b gh-pages "git@github.com:$TRAVIS_REPO_SLUG.git" "$TRAVIS_BUILD_DIR-gh-pages";
      cp -rf out/* "$TRAVIS_BUILD_DIR-gh-pages";
      rm -rf "$TRAVIS_BUILD_DIR-gh-pages/build/";
      pushd "$TRAVIS_BUILD_DIR-gh-pages";
      git config --global user.email "nabijaczleweli@gmail.com";
      git config --global user.name "Nabijaczleweli Autouploader Bot";
      git config --global push.default simple;
      git add *;
      git commit -F "$TRAVIS_BUILD_DIR/../RELEASE_UPDATE_MSG";
      git push;
      popd;
    fi
  - if [ "$TRAVIS_TAG" ]; then
      cp -r out "$TRAVIS_BUILD_DIR/../release-front-$TRAVIS_TAG";
      pushd "$TRAVIS_BUILD_DIR/..";
      rm -rf "release-front-$TRAVIS_TAG/build";
      tar -caf "release-front-$TRAVIS_TAG.tbz2" "release-front-$TRAVIS_TAG";
      rm -rf "release-front-$TRAVIS_TAG";
      popd;
    fi

deploy:
  provider: releases
  api-key:
    secure: t0cv5NJ/SLriop9iQa/+OrvQDuTP3oLI/36CmF+jo7nIEdc5onT0GS7NhdBC9Hy9UTKulrg5N24Wqm+Xze5C7Z1z1M78QDsfsX+Rbqa5q/cw6fexRcxObPrHfPTZTIcUr+THhZZRqiIl4f4cXh1iJgZAZg9FaXG3Sb+jGvprESs+PsClLl4D+jYkMJgeOVs0f+woGag0OnMZMetuWOEbShSfuVFCi3Uk27B5Al5VoVgPdt225dUks9V2gemvza4nGVFyF8YUpseNuSCLRAikRjARpiT/lx31OZon3iui0xXWZSKfcoJW+Vf/aPgioJwfr4RFxR48plbezCghje2L9z70ZfSnlEYZQSv+/s+gOYEH1DnGOEk286NuubrKvVOaq90hx/ky+OwRxxZ1vshgpt9YGjyKfjVwt2vS+5JyoUOMOUow/TtDv56vra++qr51hHIzppaNem/VtVqlI0laJppw2TC6or3uRZXC8Atu7I33sD8tdR4VGXFPdAt6lhqkWkN642+F54tJlqJgAMVWc4j8JkT9typrNn8qavL+FrhgA4VfsveMmewiaIZHw5I5RLQJ2Vzhwrf27ibUUtQ8Aih3RsCuNWKnuYd5oWqwnUydQsy4m0Fz6a3yPms4d8kYzakqbXXvMHHV84l05/20QnkvU5FmJmJcMQhwWGlmBFc=
  file: "$DEPLOY_FILE"
  skip_cleanup: true
  on:
    tags: true
    condition: $DEPLOY = true
